dubbo:
  config:
    multiple: true
  registry:
    address: nacos://127.0.0.1:8848
    timeout: 10000
  application:
    name: mining-auth-server
  protocols:
    dubbo:
      name: dubbo
      port: 28081
#    rest:
#      name: rest
#      port: 9999

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

jwt:
  secret:
    key: $&**&$
  expire:
    time: 604800